# Generated by Django 5.2.17 on 2026-09-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudcredito",
            name="tipo_credito",
            field=models.CharField(
                choices=[
                    ("por_definir", "Por definir"),
                    ("comercial", "Comercial"),
                    ("consumo", "Consumo"),
                ],
                default="por_definir",
                max_length=20,
            ),
        ),
    ]
