# Generated by Django 5.2.17 on 2026-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("cedula", "Cédula"),
                            ("ruc", "RUC"),
                            ("pasaporte", "Pasaporte"),
                        ],
                        default="cedula",
                        max_length=20,
                    ),
                ),
                ("identificacion", models.CharField(max_length=20, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
