# Generated by Django 5.2.17 on 2026-09-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="es_socio",
            field=models.BooleanField(default=False, verbose_name="es socio"),
        ),
    ]
