# Generated by Django 5.2.17 on 2026-09-02 16:19

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("solicitudes", "0002_solicitudcredito_tipo_credito"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_original",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "plazo_meses",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "tasa_interes_anual",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fecha_aprobacion",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("vigente", "Vigente"), ("cancelado", "Cancelado")],
                        default="vigente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "solicitud",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credito",
                        to="solicitudes.solicitudcredito",
                    ),
                ),
            ],
            options={
                "verbose_name": "crédito",
                "verbose_name_plural": "créditos",
                "ordering": ["-fecha_aprobacion", "-id"],
            },
        ),
    ]
